remote_theme: pmarsceill/just-the-docs
title: Openversity
description: An Open Learning Hub
url: "https://openversity.github.io"
# Define Jekyll collections
collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  docs:
    permalink: "/:collection/:path/"
    output: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
footer_content: "(c)2021 MIT license"
