title: Openversity
description: An Open Learning Hub
url: "https://openversity.github.io"
remote_theme: pmarsceill/just-the-docs
baseurl: "/docs"
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
footer_content: "(c)2021 MIT license"
